### ISSUE TITLE
Redeploy RLN contract

### ISSUE THREAD

**Issue by s1fr0** [vacp2p/rln-contract#10]
# Problem
After the recent [Poseidon refactor](https://github.com/vacp2p/rln-contract/pull/9) that sets the correct round constants, we should redeploy the contract to allow RLN users to correctly withdraw their funds, if needed.

# Acceptance criteria
- [x] Redeploy the contract

**Comment by staheri14** [comment]
Why this issue https://github.com/vacp2p/rln-contract/issues/8 is part of the acceptance criteria? what is its impact?

**Comment by staheri14** [comment]
The issue description is about redeployment due to the hash function update, and the fee option is not directly relevant. Putting it in the acceptance criteria gives a false signal of the fee option being a blocker.  

Either we shall revise the issue description to list all the issues that will result in contract redeployment, or the acceptance criteria is better to be revised. And I think the second solution one more sense since there might be multiple redeployments e.g., after implementing a more secure slashing strategy which will impact the contract interface as well.

**Comment by AtHeartEngineer** [comment]
Where is this contract deployed to now? Mainnet? Testnet?

**Comment by rymnc** [comment]
Redeployed on Sepolia - https://github.com/vacp2p/rln-contract/blob/main/deployments/sepolia/RLN.json
